[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
sea-orm = {version = "1.1.4", features = ["sqlx-mysql", "runtime-async-std-native-tls"]}
futures = "0.3.31"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
fake = "3.1.0"
